Algoritmo "converter_a_e_b"
// 
//  
// Descrição   : Trocar valores de A e B
// Autor(a)    : Kewyn
// Data atual  : 09/03/2021
Var
// Seção de Declarações das variáveis 
a,b,c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-15
b<-30
escreval("o valor de a é")
escreval(" o valor de b é")
c<-a
a<-b
b<-c
escreval("O valor de a é:",a)
escreval("O valor de b é",b)

Fimalgoritmo