Algoritmo "conversao_celsius_fahrenheit"
// 
//  
// Descrição   : Coversão de fahreinheit para celsius
// Autor(a)    : Kewyn
// Data atual  : 09/03/2021
Var
// Seção de Declarações das variáveis 
c,f:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva o valor em fahreneit:")
leia(f)
c<-(5 * (f-32) / 9)
escreval("O valor em celsius é:",c)

Fimalgoritmo